// Generated by https://quicktype.io

export interface ArticleSpaceType {
    id:          number;
    title:       string;
    url:         string;
    imageUrl:    string;
    newsSite:    NewsSite;
    summary:     string;
    publishedAt: string;
    updatedAt:   string;
    featured:    boolean;
    launches:    Launch[];
    events:      any[];
}

export interface Launch {
    id:       string;
    provider: string;
}

export enum NewsSite {
    Arstechnica = "Arstechnica",
    NASASpaceflight = "NASASpaceflight",
    SpaceNews = "SpaceNews",
}
